### ISSUE TITLE
Bug in model_utils.degree_correlation

### ISSUE THREAD

**Issue by smithara** [ancklo/ChaosMagPy#2]
https://github.com/ancklo/ChaosMagPy/blob/3e2375376571058b59f2ef4c8f41285ef1499ebd/chaosmagpy/model_utils.py#L735

Two minor things that prevent it from running:
 - Change value checking to `len(coeffs_1) != len(coeffs_2)` in place of `is not`
 - `nmax` needs to be forced to be int, `nmax = int(np.sqrt(len(coeffs_1) + 1) - 1)`
I haven't tested it otherwise but it looks right

Btw, thanks for providing the library, it's been useful to me :)

**Comment by ancklo** [comment]
Thanks for pointing this out, you're completely right :)
I implemented the suggested changes. You can get an updated version from PyPI now.

I'm happy to hear that it's useful. Please let me know if you encounter more bugs, feedback is very welcome :D
